<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/Clase7_Elementos_%C3%9Anicos_y_sus_Conteos_Copias_y_Vistas7_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
# creamos array
survey_responses = np.array(["bueno", "excelente", "malo",
                             "bueno", "malo", "excelente",
                             "bueno", "bueno", "malo",
                             "excelente"])

# imprimios valores únicos del array
print(np.unique(survey_responses))

['bueno' 'excelente' 'malo']


In [4]:
# seleccionamos valores únicos y los contamos
unique_elements, counts = np.unique(survey_responses, return_counts=True)
print(unique_elements)
print(counts)

['bueno' 'excelente' 'malo']
[4 3 3]


### Copias y Vistas

In [8]:
# Al crear una vista de un array,
# las modificaciones del array también afectan la vista creada

array_x = np.arange(10)
view_x = array_x[1:3]
print(array_x)
print(view_x)
array_x[1:3] = [10,11]
print(array_x)
print(view_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[10 11]


In [12]:
# Al crear una copia de un array,
# las modificaciones del array no afectan la copia creada

array_x = np.arange(10)
copy_x = array_x[[1,2]]
print(array_x)
print(copy_x)
array_x[1:3] = [10,11]
print(array_x)
print(copy_x)

[0 1 2 3 4 5 6 7 8 9]
[1 2]
[ 0 10 11  3  4  5  6  7  8  9]
[1 2]
