<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/Clase3_Arrays_en_NumPy3_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
array = np.array([[1,2,3],[4,5,6]]) #crea matriz 2x3, 2 dimensiones
print(array)
print(array.ndim)
print(array.shape)
print(array.dtype)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
int64


In [4]:
z = np.array(3, dtype=np.uint8) # crea arreglo escalar, tipo de dato uint8
print(z)

3


In [5]:
double_array = np.array([1,2,3], dtype='d') # crea arreglo con tipo dato float64 = 'd' (decimal)
print(double_array)

[1. 2. 3.]


In [6]:
z = z.astype(np.float64) # convierte dato a float64

In [7]:
array = np.array([[1,2,3], [4,5,6]])  # suma de array
add = np.sum(array)
print(add)

21


In [8]:
array = np.array([[1,2,3], [4,5,6]])
sum = np.sum(array)
print(sum)

21


In [10]:
mean = np.mean(array) # calcula la media de array
print(mean)

3.5


In [11]:
std = np.std(array) # calcula la desviación estandar std de array
print(std)

1.707825127659933
