<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/Clase5_Indexaci%C3%B3n_y_Slicing5_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
import numpy as np

In [20]:
# segunda y última posición de un array
array = np.array([10, 20, 30, 40, 50])
print(array[1])
print(array[-1])

20
50


In [21]:
# segunda y tercera posición de un array
print(array[1:4])

[20 30 40]


In [22]:
# segunda y posici´n más allá del último elemento del array
print(array[1:7])

[20 30 40 50]


In [23]:
# posiciones por fuera del array
print(array[-1:-7])

[]


In [24]:
# verificar si valores en array son mayores que
array = np.array([10, 20, 30, 40, 50])
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [25]:
# posiciones mediante variable que tiene los índices de las posiciones
index = [2,0,3]
print(array[index])

[30 10 40]


In [26]:
# generar matriz 3x3 con númertos aleatorios
array = np.random.randint(1, 10, size=(3,3))
print(array)
print(array[0,1]) # miramos valor en posición 0,1

[[6 5 5]
 [2 2 8]
 [4 4 4]]
5


In [27]:
# formamos un pequeño array (matriz) del array  (matriz) anterior
print(array[:2,:2])

[[6 5]
 [2 2]]
