<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/Clase11_Ejercicios_en_NumPy11_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

### 1. Operaciones Básicas con Arrays

In [8]:
array1 = np.array([10, 20, 30, 40])
array2 = np.array([1, 2, 3, 4])

suma = array1 + array2
resta = array1 - array2
multiplicacion = array1 * array2
division = array1 / array2

print("Suma: ",suma)
print("Resta: ",resta)
print("Multiplicación :",multiplicacion)
print("Dvisión :", division)

Suma:  [11 22 33 44]
Resta:  [ 9 18 27 36]
Multiplicación : [ 10  40  90 160]
Dvisión : [10. 10. 10. 10.]


### 2. Cálculos Estadísticos en Arrays



In [13]:
datos = np.array([23, 76, 35, 67, 89, 45, 68, 79, 35])

media = np.mean(datos)
mediana = np.median(datos)
varianza = np.var(datos)
desviacion = np.std(datos)

print("Media:", media)
print("Mediana:", mediana)
print("Varianza:", varianza)
print("Desviación estándar:", desviacion)

Media: 57.44444444444444
Mediana: 67.0
Varianza: 484.02469135802465
Desviación estándar: 22.000561160071


### 3. Operaciones Matriciales

In [14]:
matriz1 = np.array([[1,2], [3,4]])
matriz2 = np.array([[3,4],[5,6]])

suma_matrices = matriz1 + matriz2
resta_matrices = matriz1 + matriz2
producto_matrices = np.dot(matriz1, matriz2)
inversa_matriz1 = np.linalg.inv(matriz1)

print("Suma de matrices:\n", suma_matrices)
print("Resta de matrices:\n", resta_matrices)
print("Producto de matrices:\n", producto_matrices)
print("Inversa de matriz1:\n", inversa_matriz1)

Suma de matrices:
 [[ 4  6]
 [ 8 10]]
Resta de matrices:
 [[ 4  6]
 [ 8 10]]
Producto de matrices:
 [[13 16]
 [29 36]]
Inversa de matriz1:
 [[-2.   1. ]
 [ 1.5 -0.5]]


### 4. Resolución de un Sistema de Ecuaciones Lineales

In [15]:
A = np.array([[2,3],[1,2]])
b = np.array([8,5])

x = np.linalg.solve(A, b)
print("Solución del sistema de ecuaciones:", x)

Solución del sistema de ecuaciones: [1. 2.]


### 5. Simulación de Datos
Instrucción: Genera un array de 1000 números aleatorios que sigan una distribución normal con media 0 y desviación estándar 1. Calcula la media y desviación estándar del array generado.

In [16]:
datos_simulados = np.random.normal(0, 1, 1000)
media_simulada = np.median(datos_simulados)
desviacion_simulada = np.std(datos_simulados)

print("Media de los datos simulados:", media_simulada)
print("Desviación estándar de los datos simulados:", desviacion_simulada)

Media de los datos simulados: -0.03325040683141543
Desviación estándar de los datos simulados: 0.9702230084078913
