<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/Clase8_Transformaci%C3%B3n_de_Arrays_Reshape_y_Manipulaci%C3%B3n8_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Transpuesta de una matriz
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix_transp = matrix.T  # calculamos transpuesta de matriz
print(matrix, "\n")
print(matrix_transp)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
# Reshape de una matriz
array = np.arange(1,13)
array_reshaped = array.reshape(3,4) # reformamos array en una matriz de 3x4
print(array)
print(array_reshaped)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [5]:
# Intento de Reshape de una matriz, sin coindidencia de dimensionalidad.
array_error = np.arange(1,15)
array_reshaped = array.reshape(3,4) # reformamos array en una matriz de 3x4
print(array)
print(array_reshaped)

ValueError: cannot reshape array of size 14 into shape (3,4)

In [6]:
# transformamos un array en un array invertido
reversed_array = array[::-1]
print(array)
print(reversed_array)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[14 13 12 11 10  9  8  7  6  5  4  3  2  1]


### Flattening convertir un array multidimensional en uno unidimensional

In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
flattened_matrix = matrix.flatten()
print(matrix, "\n")
print(flattened_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[1 2 3 4 5 6 7 8 9]
