<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/Clase4_Introducci%C3%B3n_al_%C3%A1lgebra_lineal_con_NumPy4_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [5]:
# suma de matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
suma = A + B
print("Suma de matrices:\n ", suma)

Suma de matrices:
  [[ 6  8]
 [10 12]]


In [7]:
# Multiplicación de matrices
producto = np.dot(A, B)
print("Producto de matrices: \n", producto)

Producto de matrices: 
 [[19 22]
 [43 50]]


In [10]:
# Transposición de matriz
transpuesta = np.transpose(A)
print("Transpuesta de matriz: \n", transpuesta)

Transpuesta de matriz: 
 [[1 3]
 [2 4]]


In [12]:
# Determinante de una matriz
determinante = np.linalg.det(A)
print(determinante)

-2.0000000000000004


In [13]:
# Inversa de una matriz
inversa = np.linalg.inv(A)
print("Inversa de una matriz: \n", A)

Inversa de una matriz: 
 [[1 2]
 [3 4]]


In [15]:
# Solución de sistemas de ecuaciones lineales
B = np.array([1,2])
X = np.linalg.solve(A, B)
print("solución del sistema AX = B: \n", X)


solución del sistema AX = B: 
 [0.  0.5]
