<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/Clase10_C%C3%A1lculos_Matriciales_en_NumPy10_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
# Suma de matrices
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

# Suma
sum = A + B
print(A)
print(B)
print(sum)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]


In [4]:
# multiplicación de matrices
product = np.dot(A, B)
print(product)

[[19 22]
 [43 50]]


In [5]:
# Determinante o inversa de una matriz
A = np.array([[1,2],[3,4]])
det_A = np.linalg.det(A)
inv_A = np.linalg.inv(A)
print(A)
print(det_A)
print(inv_A)

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [6]:
# Resolución de sistema de ecuación Ax = b
b = np.array([9,11])
x = np.linalg.solve(A, b)
print(x)

[-7.  8.]
