<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/Clase9_Caso_Pr%C3%A1ctico_de_An%C3%A1lisis_de_Datos9_32.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# Paso 1: Crear arrays con datos de ventas mensuales
meses = np.array(['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio',
                  'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'])
ventas_A = np.array([150, 200, 250, 300, 220, 210, 180, 190, 230, 240, 280, 300])
ventas_B = np.array([180, 210, 230, 250, 270, 260, 240, 250, 270, 290, 310, 330])
ventas_C = np.array([200, 220, 240, 260, 280, 300, 320, 340, 360, 380, 400, 420])

In [3]:
# Venta de cada producto total
total_ventas_A = np.sum(ventas_A)
total_ventas_B = np.sum(ventas_B)
total_ventas_C = np.sum(ventas_C)

print("\n La venta total de A es: ", total_ventas_A)
print("\n La venta total de B es: ", total_ventas_B)
print("\n La venta total de C es: ", total_ventas_C)


 La venta total de A es:  2750

 La venta total de B es:  3090

 La venta total de C es:  3720


In [4]:
# Venta de cada mes
mes_ventas_A = np.vstack((meses, ventas_A))
mes_ventas_B = np.vstack((meses, ventas_B))
mes_ventas_C = np.vstack((meses, ventas_C))

print(f"Ventas A mensuales: {mes_ventas_A}")
print(f"Ventas B mensuales: {mes_ventas_B}")
print(f"Ventas C mensuales: {mes_ventas_C}")

Ventas A mensuales: [['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
  'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
 ['150' '200' '250' '300' '220' '210' '180' '190' '230' '240' '280' '300']]
Ventas B mensuales: [['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
  'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
 ['180' '210' '230' '250' '270' '260' '240' '250' '270' '290' '310' '330']]
Ventas C mensuales: [['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
  'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
 ['200' '220' '240' '260' '280' '300' '320' '340' '360' '380' '400' '420']]


In [9]:
# ventas mensuales invertidas de dic a ene
inverted_ventas_A = ventas_A[::-1]
inverted_ventas_B = ventas_B[::-1]
inverted_ventas_C = ventas_C[::-1]
print(inverted_ventas_A)
print(inverted_ventas_B)
print(inverted_ventas_C)

[300 280 240 230 190 180 210 220 300 250 200 150]
[330 310 290 270 250 240 260 270 250 230 210 180]
[420 400 380 360 340 320 300 280 260 240 220 200]
