<a href="https://colab.research.google.com/github/electrojam/Curso-de-Python-para-Ciencia-de-Datos/blob/main/numpy_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd

In [3]:
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [5]:
vector = np.array([30, 29, 35, 31, 33, 36, 42])
print(vector)

[30 29 35 31 33 36 42]


In [7]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
tensor = np.array([[[1,2],[3,4],[5,6],[7,8]]])  # tensor 3 dim
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [17]:
array_arange = np.arange(10) # arreglo con arange
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
eye_matriz = np.eye(6) # matriz identidad de 6x6
print(eye_matriz)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [20]:
diag_matrix = np.diag([1,2,3,4,5,6,7]) # matriz diagonal
print(diag_matrix)

[[1 0 0 0 0 0 0]
 [0 2 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 4 0 0 0]
 [0 0 0 0 5 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 7]]


In [24]:
random_matriz = np.random.random((2,3)) # matriz random de 2x3 tupla,
print(random_matriz)

[[0.93819655 0.26448578 0.27810281]
 [0.45733144 0.80285502 0.4948359 ]]
